# Zjazd 3, część 1 — NumPy

**Autor:** Agata Hutor

## Ćwiczenie 1: Tworzenie tablic

### Import

In [23]:
import numpy as np

### Tworzenie tablic

##### 1. Z listy

In [24]:
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


##### 2. Zera — 10 elementów

In [25]:
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


##### 3. Jedynki — macierz 3×5

In [26]:
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


##### 4. Sekwencja od 0 do 100, co 10

In [27]:
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


##### 5. 7 równomiernych punktów od 0 do 1

In [28]:
procenty = np.linspace(0, 1, 7)
print(f"Procenty: {procenty}")

Procenty: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


##### 6. 20 losowych ocen od 2 do 5

In [29]:
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


### Atrybuty

In [30]:
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


## Ćwiczenie 2: Indeksowanie i slicing

#### Tablica 1D

In [31]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy:                     0     1    2    3    4    5    6    7    8    9   10   11
# Miesiące:                  Sty  Lut  Mar  Kwi  Maj  Cze  Lip  Sie  Wrz  Paź  Lis  Gru

1. Sprzedaż w styczniu

In [32]:
print(f"Sprzedaż w styczniu: {miesiace_sprzedaz[0]}")

Sprzedaż w styczniu: 120


2. Sprzedaż w grudniu

In [33]:
print(f"Sprzedaż w grudniu: {miesiace_sprzedaz[-1]}")

Sprzedaż w grudniu: 221


3. Sprzedaż w Q1 (styczeń-marzec)

In [34]:
print(f"Sprzedaż w Q1: {miesiace_sprzedaz[0:3]}")

Sprzedaż w Q1: [120 135  98]


4. Sprzedaż w Q4 (październik-grudzień)

In [35]:
print(f"Sprzedaż w Q4: {miesiace_sprzedaz[-3:]}")

Sprzedaż w Q4: [143 198 221]


5. Sprzedaż co drugi miesiąc

In [36]:
print(f"Sprzedaż co drugi miesiąc: {miesiace_sprzedaz[::2]}")

Sprzedaż co drugi miesiąc: [120  98 167 201 156 198]


6. Sprzedaż od tyłu 

In [37]:
print(f"Sprzedaż od tyłu: {miesiace_sprzedaz[::-1]}")

Sprzedaż od tyłu: [221 198 143 156 178 201 189 167 142  98 135 120]


#### Macierz 2D

In [38]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
    [120, 145, 167],   # Produkt A
    [89,  102, 95],    # Produkt B
    [234, 267, 289],   # Produkt C
    [56,  78,  91],    # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

1. Sprzedaż Produktu A w Q2

In [39]:
print(f'Sprzedaż Produktu A w Q2: {dane[0, 1]}')

Sprzedaż Produktu A w Q2: 145


2. Cała sprzedaż Produktu C

In [40]:
print(f'Sprzedaż Produktu C: {dane[2, :]}')

Sprzedaż Produktu C: [234 267 289]


3. Sprzedaż wszystkich produktów w Q1

In [41]:
print(f'Sprzedaż produktów w Q1 : {dane[:, 0]}')

Sprzedaż produktów w Q1 : [120  89 234  56]


4. Sprzedaż Produktów B i C w Q2 i Q3

In [42]:
print(f'Sprzedaż Produktów B i C w Q2 i Q3: {dane[1:3, 1:3]}')

Sprzedaż Produktów B i C w Q2 i Q3: [[102  95]
 [267 289]]


## Ćwiczenie 3: Operacje wektorowe — analiza biznesowa 

In [43]:
import numpy as np

# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
         'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']

ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

1. Podstawowe statystyki cenowe 

In [44]:
print(f'''Średnia cena: {ceny.mean()},
Najdroższy produkt: {nazwy[ceny.argmax()]} {ceny.max()} ,
Najtańszy produkt: {nazwy[ceny.argmin()]} {ceny.min()}
''')

Średnia cena: 1171.0,
Najdroższy produkt: Laptop 3499 ,
Najtańszy produkt: Ładowarka 89



2. Wartość magazynu

In [45]:
wartosc_produktu = ceny * ilosci_magazyn

j = 0
for i in wartosc_produktu:
    print(nazwy[j], ":", wartosc_produktu[j])
    j += 1


print(f'Łączna wartość magazynu: {wartosc_produktu.sum()}')


Laptop : 52485
Tablet : 79758
Smartfon : 194922
Słuchawki : 54444
Ładowarka : 27768
Klawiatura : 22161
Mysz : 25929
Monitor : 34477
Kamera : 26955
Drukarka : 30566
Łączna wartość magazynu: 549465


3. Analiza cenowa

In [46]:
print("Ceny po rabacie 15% (promocja świąteczna):")
rabat_15 = ceny * 0.85

j = 0
for i in rabat_15:
    print(nazwy[j], ":", rabat_15[j])
    j += 1

print("\nCeny z VAT 23%:")
VAT = ceny * 1.23

j = 0
for i in VAT:
    print(nazwy[j], ":", VAT[j])
    j += 1


produkty_1000 = (ceny > 1000).sum()
print('\nProdukty kosztujące powyżej 1000 zł:', produkty_1000)



Ceny po rabacie 15% (promocja świąteczna):
Laptop : 2974.15
Tablet : 1614.1499999999999
Smartfon : 2124.15
Słuchawki : 296.65
Ładowarka : 75.64999999999999
Klawiatura : 211.65
Mysz : 109.64999999999999
Monitor : 1274.1499999999999
Kamera : 509.15
Drukarka : 764.15

Ceny z VAT 23%:
Laptop : 4303.7699999999995
Tablet : 2335.77
Smartfon : 3073.77
Słuchawki : 429.27
Ładowarka : 109.47
Klawiatura : 306.27
Mysz : 158.67
Monitor : 1843.77
Kamera : 736.77
Drukarka : 1105.77

Produkty kosztujące powyżej 1000 zł: 4


4. Filtrowanie

In [47]:
print("Produkty z oceną >= 4.5:")

maska_oceny = oceny_klientow >= 4.5

j = 0
for i in maska_oceny:
    if i:
        print(nazwy[j], ":", ceny[j])
    j += 1

print("\nProdukty poniżej 200 zł:")

maska_ceny = ceny < 200

j = 0
for i in maska_ceny:
    if i:
        print(nazwy[j], ":", ilosci_magazyn[j])
    j += 1


Produkty z oceną >= 4.5:
Laptop : 3499
Smartfon : 2499
Słuchawki : 349
Monitor : 1499

Produkty poniżej 200 zł:
Ładowarka : 312
Mysz : 201


5. Analiza zapasów

In [48]:
print("Produkty z niskim stanem magazynowym (<30):")

maska_magazyn = ilosci_magazyn < 30

j = 0
for i in maska_magazyn:
    if i:
        print(nazwy[j])
    j += 1

wartosci = ceny * ilosci_magazyn
suma = 0

j = 0
for i in maska_magazyn:
    if i:
        suma += wartosci[j]
    j += 1

print("\nŁączna wartość:", suma)

total = wartosci.sum()
procent = (suma / total) * 100

print("\nProcent magazynu:", procent, "%")

Produkty z niskim stanem magazynowym (<30):
Laptop
Monitor

Łączna wartość: 86962

Procent magazynu: 15.826667758637946 %


6. Analiza korelacji cena-ocena

In [49]:
print("Produkty - okazje:")

maska = (oceny_klientow >= 4.5) & (ceny < 1000)

j = 0
for i in maska:
    if i:
        print(nazwy[j], ":", ceny[j])
    j += 1

maska_high = oceny_klientow >= 4.0

suma = 0
count = 0

j = 0
for i in maska_high:
    if i:
        suma += ceny[j]
        count += 1
    j += 1

avg_high = suma / count

maska_low = oceny_klientow < 4.0

suma = 0
count = 0

j = 0
for i in maska_low:
    if i:
        suma += ceny[j]
        count += 1
    j += 1

avg_low = suma / count

print("\nŚrednia cena (>= 4.0):", avg_high)
print("Średnia cena (< 4.0):", avg_low)

Produkty - okazje:
Słuchawki : 349

Średnia cena (>= 4.0): 1446.142857142857
Średnia cena (< 4.0): 529.0


## Ćwiczenie 4: Benchmark — lista vs NumPy

In [50]:
import time

# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

# Test 1: Pomnóż przez 2
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start

print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista:  117.4 ms
NumPy:  1.8 ms
NumPy jest 66× szybszy!


In [51]:
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start

start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start

print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista:  14.4 ms
NumPy:  1.2 ms
NumPy jest 12× szybszy!


In [52]:
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start

print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista:  82.1 ms
NumPy:  2.1 ms
NumPy jest 39× szybszy!
