# Zjazd 3, część 2 — NumPy zaawansowane

**Autor:** Agata Hutor

In [1]:
import numpy as np


## Ćwiczenie 1: Broadcasting — zastosowania biznesowe

In [2]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99],    # Produkt A
                  [49.99, 52.99, 47.99],    # Produkt B
                  [14.99, 15.99, 13.99],    # Produkt C
                  [99.99, 104.99, 94.99]])  # Produkt D

sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}")  # (4, 3)

Kształt macierzy: (4, 3)


Zadanie 1a: Stwórz nowy array z cenami podniesionymi o 5% (inflacja). Wyświetl wynik.

In [4]:
ceny_inflacja = ceny * 1.05

print(f"Ceny po inflacji:\n {ceny_inflacja} ")

Ceny po inflacji:
 [[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]] 


Zadanie 1b — ceny po rabacie (różne dla sklepów)

In [5]:
rabaty = np.array([0.10, 0.05, 0.15])

ceny_rabat = ceny * (1 - rabaty)

print(f"Ceny po rabacie: \n {ceny_rabat}")


Ceny po rabacie: 
 [[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


Zadanie 1c: Oblicz koszt zakupu każdego produktu. Każdy produkt ma inną marżę: A=30%, B=40%, C=25%, D=50%.

In [6]:
marza = np.array([[0.30], [0.40], [0.25], [0.50]])

koszt = ceny / (1 + marza)

print(f"Koszt zakupu:\n {koszt}")

Koszt zakupu:
 [[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


Zadanie 1d: Wyświetl najtańszy sklep dla każdego produktu.

In [24]:
indeksy = ceny.argmin(axis=1)

print(f"Najtańszy sklep dla każdego produktu: \n")

j = 0
for i in indeksy:
    print("Produkt", produkty[j], ":", sklepy[i])
    j += 1

Najtańszy sklep dla każdego produktu: 

Produkt A : Online
Produkt B : Online
Produkt C : Online
Produkt D : Online


## Ćwiczenie 2: Reshape i łączenie danych

Zadanie 2a — Reshape

In [8]:
# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

# Przekształć na kwartały (4 kwartały × 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


Zadanie 2b — Stacking

In [9]:
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])

# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


Zadanie 2c — Praktyczne

In [12]:
# 1. Reshape na macierz 6x2
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])

sprzedaz = sprzedaz_flat.reshape(6, 2)

print(f"Macierz sprzedaży:\n {sprzedaz}")

Macierz sprzedaży:
 [[100 200]
 [150 300]
 [250 180]
 [120 220]
 [170 310]
 [260 190]]


In [13]:
# 2. Średnia sprzedaż per produkt (axis=1)
srednia = sprzedaz.mean(axis=1) #operacja po wierszach

print(f"Średnia sprzedaż per produkt:\n {srednia}")


Średnia sprzedaż per produkt:
 [150. 225. 215. 170. 240. 225.]


In [15]:
# 3. Zmiana między miesiącami
zmiana = sprzedaz[:, 1] - sprzedaz[:, 0] #wszystkie wiersze (:) i kolumnę 1

print(f"Zmiana sprzedaży (miesiąc 2 - miesiąc 1): \n {zmiana}")

Zmiana sprzedaży (miesiąc 2 - miesiąc 1): 
 [100 150 -70 100 140 -70]


Zadanie 2d — Flatten i concatenate

In [17]:
# 1. Spłaszcz ją z powrotem do wektora (.flatten())
wektor = dane_flat.flatten()

print(f"Wektor: {wektor}")


Wektor: [120 135  98 142 167 189 201 178 156 143 198 221]


In [18]:
# 2. Dodanie 13. miesiąca
nowy_miesiac = np.array([235])

wektor_rozszerzony = np.concatenate([wektor, nowy_miesiac])

print(f"Po dodaniu 13. miesiąca: \n {wektor_rozszerzony}")

Po dodaniu 13. miesiąca: 
 [120 135  98 142 167 189 201 178 156 143 198 221 235]


## Ćwiczenie 3: Analiza danych finansowych

In [19]:
np.random.seed(2026)

# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])

# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

### Zadanie 3a: Analiza wynagrodzeń

1. Oblicz średnią, medianę i odchylenie standardowe pensji

In [20]:
srednia = pensje.mean()
mediana = np.median(pensje)
std = pensje.std()

print("Średnia:", srednia)
print("Mediana:", mediana)
print("Odchylenie:", std)

Średnia: 6425.0
Mediana: 6050.0
Odchylenie: 1616.9029037020127


2. Wyświetl imiona osób zarabiających powyżej średniej

In [21]:
prac_np = np.array(pracownicy)

print("Powyżej średniej:")

maska = pensje > srednia

j = 0
for i in maska:
    if i:
        print(prac_np[j])
    j += 1

Powyżej średniej:
Jan
Marek
Zofia


3. Wyświetl imiona osób zarabiających poniżej mediany

In [22]:
print("Poniżej mediany:")

maska = pensje < mediana

j = 0
for i in maska:
    if i:
        print(prac_np[j])
    j += 1

Poniżej mediany:
Anna
Ewa
Piotr
Tomek


4. Oblicz rozstęp (max - min) i rozstęp międzykwartylowy (IQR)

In [23]:
rozstep = pensje.max() - pensje.min()
iqr = np.percentile(pensje, 75) - np.percentile(pensje, 25)

print("\nRozstęp:", rozstep)
print("IQR:", iqr)


Rozstęp: 4900
IQR: 2200.0


### Zadanie 3b: System premii (np.where)

In [26]:
premie = np.where(oceny >= 4.5, 2000,
         np.where(oceny >= 4.0, 1000, 0))

nowe_pensje = pensje + premie

print("Premie:", premie)
print("Nowe pensje:", nowe_pensje)

idx = premie.argmax()
print("Najwyższa premia:", prac_np[idx])

Premie: [1000    0 2000 1000 2000    0 1000    0]
Nowe pensje: [ 6500  7200  6800 10100  8300  4200  9500  5800]
Najwyższa premia: Ewa


### Zadanie 3c: Ranking (argsort)

In [28]:
kolejnosc = np.argsort(pensje)[::-1]

print("Ranking:")

for i, idx in enumerate(kolejnosc, 1):
    print(i, prac_np[idx], pensje[idx], "staż:", staz[idx])

Ranking:
1 Marek 9100 staż: 15
2 Zofia 8500 staż: 12
3 Jan 7200 staż: 8
4 Kasia 6300 staż: 5
5 Tomek 5800 staż: 4
6 Anna 5500 staż: 3
7 Ewa 4800 staż: 2
8 Piotr 4200 staż: 1


### Zadanie 3d: Korelacja

In [29]:
corr_staz_pensja = np.corrcoef(staz, pensje)[0, 1]
corr_staz_ocena = np.corrcoef(staz, oceny)[0, 1]

print("Korelacja staż-pensja:", corr_staz_pensja)
print("Korelacja staż-ocena:", corr_staz_ocena)

if abs(corr_staz_pensja) > abs(corr_staz_ocena):
    print("Silniejsza zależność: staż-pensja")
else:
    print("Silniejsza zależność: staż-ocena")

Korelacja staż-pensja: 0.987862864584301
Korelacja staż-ocena: 0.04198471605953068
Silniejsza zależność: staż-pensja


### Zadanie 3e: Analiza sprzedaży (broadcasting)

In [31]:
ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol

print("\nPrzychód:")
print(przychod)

suma_produkty = przychod.sum(axis=1)
idx = suma_produkty.argmax()

print("Najlepszy produkt:", produkty_nazwy[idx])

suma_miesiace = przychod.sum(axis=0)
idx = suma_miesiace.argmax()

print("Najlepszy miesiąc:", idx)

#trend
pierwsze = przychod[:, :3].sum()
ostatnie = przychod[:, 3:].sum()

print("Pierwsze 3 miesiące:", pierwsze)
print("Ostatnie 3 miesiące:", ostatnie)

if ostatnie > pierwsze:
    print("Trend rosnący")
else:
    print("Trend malejący")


Przychód:
[[ 73500 539000 161000 339500 339500 171500]
 [244800 316800 358200  86400 270000  84600]
 [ 67500 290000 387500 327500 420000 452500]
 [ 10200   8700   6750  13200  19800  12000]]
Najlepszy produkt: Smartfon
Najlepszy miesiąc: 1
Pierwsze 3 miesiące: 2463950
Ostatnie 3 miesiące: 2536500
Trend rosnący


## Ćwiczenie 4: Generowanie danych

In [32]:
np.random.seed(42)

# Wygeneruj dane o 100 klientach sklepu:
# - wiek: rozkład normalny, średnia 35, std 10, zaokrąglony do int, min 18
# - wydatki_miesiecznie: rozkład normalny, średnia 500, std 200, min 0
# - liczba_wizyt: rozkład Poissona, lambda=5

# Podpowiedź: np.clip() ogranicza wartości do zakresu
wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)

### 1. Statystyki opisowe każdej zmiennej (mean, median, std, min, max)

In [33]:
print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}, std: {wiek.std():.1f}, min: {wiek.min()}, max: {wiek.max()}")

print(f"Wydatki — średnia: {wydatki.mean():.1f}, mediana: {np.median(wydatki):.1f}, std: {wydatki.std():.1f}, min: {wydatki.min():.1f}, max: {wydatki.max():.1f}")

print(f"Wizyty — średnia: {wizyty.mean():.1f}, mediana: {np.median(wizyty):.1f}, std: {wizyty.std():.1f}, min: {wizyty.min()}, max: {wizyty.max()}")

Wiek — średnia: 33.6, mediana: 33.0, std: 8.6, min: 18, max: 53
Wydatki — średnia: 504.5, mediana: 516.8, std: 189.8, min: 116.2, max: 1044.0
Wizyty — średnia: 4.9, mediana: 5.0, std: 2.2, min: 1, max: 11


### 2. Korelacja wiek vs wydatki

In [38]:
corr_wiek_wydatki = np.corrcoef(wiek, wydatki)[0, 1]

print("Korelacja wiek-wydatki:", corr_wiek_wydatki)

Korelacja wiek-wydatki: -0.12009183441777695


### 3. Korelacja wizyty vs wydatki

In [35]:
corr_wizyty_wydatki = np.corrcoef(wizyty, wydatki)[0, 1]

print("Korelacja wizyty-wydatki:", corr_wizyty_wydatki)

Korelacja wizyty-wydatki: -0.15884985147948125


### 4. Segmentacja klientów za pomocą np.where

In [36]:
sr = wydatki.mean()
sd = wydatki.std()

segment = np.where(
    wydatki > sr + sd, "WYSOKI",
    np.where(wydatki < sr - sd, "NISKI", "ŚREDNI")
)

print("Segmenty (pierwsze 10):")
print(segment[:10])

Segmenty (pierwsze 10):
['NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI']


### 5. Ile klientów w każdym segmencie? Użyj np.unique(..., return_counts=True)

In [37]:
unikalne, liczby = np.unique(segment, return_counts=True)

print("Liczba klientów w segmentach:")

j = 0
for i in unikalne:
    print(unikalne[j], ":", liczby[j])
    j += 1

Liczba klientów w segmentach:
NISKI : 17
WYSOKI : 12
ŚREDNI : 71
